version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.17.9
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - cluster.name=rmd-homework
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    container_name: kibana
    image: kibana:7.17.9
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  logstash:
    container_name: logstash
    image: logstash:7.17.9
    ports: 
      - 5044:5044
    volumes:
      - ./pipelines/pipeline.yml:/usr/share/logstash/config/pipelines.yml
#      - /var/log/nginx/access.log:/var/log/nginx/access.log
      - ./pipelines/config.conf:/usr/share/logstash/config/config.conf
    depends_on:
      - elasticsearch
  filebeat:
    container_name: filebeat
    image: elastic/filebeat:8.12.2
    volumes:
      - /var/log/nginx/access.log:/var/log/nginx/access.log:ro
      - ./pipelines/filebeat.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - elasticsearch
      - logstash
volumes:
  elasticsearch-data:
